# Generated by Django 3.2.3 on 2021-08-11 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primerEstado', models.BooleanField()),
                ('nombre', models.CharField(max_length=32)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('LT', 'Lider Tecnico'), ('LF', 'Lider Funcional'), ('RC', 'Representante Cliente')], max_length=2, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlProyecto.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicial', models.BooleanField()),
                ('nombre', models.CharField(max_length=32)),
                ('descripcion', models.TextField(null=True)),
                ('anterior', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ControlProyecto.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=16, unique=True)),
                ('proyectos', models.ManyToManyField(through='ControlProyecto.RolUsuario', to='ControlProyecto.Proyecto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ControlProyecto.workflow')),
            ],
        ),
        migrations.AddField(
            model_name='rolusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlProyecto.usuario'),
        ),
        migrations.CreateModel(
            name='ResponsablesEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlProyecto.estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlProyecto.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuarios',
            field=models.ManyToManyField(through='ControlProyecto.RolUsuario', to='ControlProyecto.Usuario'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlProyecto.proyecto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlProyecto.tipoitem')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlProyecto.item'),
        ),
        migrations.AddField(
            model_name='estado',
            name='responsables',
            field=models.ManyToManyField(blank=True, through='ControlProyecto.ResponsablesEstado', to='ControlProyecto.Usuario'),
        ),
        migrations.AddField(
            model_name='estado',
            name='siguiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ControlProyecto.estado'),
        ),
    ]
