# Generated by Django 3.2.3 on 2021-07-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlProyecto', '0002_alter_rolusuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
