# Generated by Django 3.2.3 on 2021-08-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlProyecto', '0003_auto_20210810_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='siguientes',
            field=models.ManyToManyField(blank=True, to='ControlProyecto.Workflow'),
        ),
    ]
