# Generated by Django 3.2.3 on 2021-08-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlProyecto', '0004_alter_workflow_siguientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='usuarios',
            field=models.ManyToManyField(blank=True, through='ControlProyecto.RolUsuario', to='ControlProyecto.Usuario'),
        ),
    ]
