# Generated by Django 3.2.3 on 2021-07-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlProyecto', '0004_alter_workflow_siguientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='siguientes',
            field=models.ManyToManyField(blank=True, related_name='_ControlProyecto_workflow_siguientes_+', to='ControlProyecto.Workflow'),
        ),
    ]
