# Generated by Django 3.2.3 on 2021-07-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlProyecto', '0005_alter_workflow_siguientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='inicial',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
