# Generated by Django 3.2.3 on 2021-08-11 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlProyecto', '0005_alter_proyecto_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='primerEstado',
            new_name='inicial',
        ),
    ]
