# Generated by Django 3.2.3 on 2021-08-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlProyecto', '0007_auto_20210811_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
