# Generated by Django 3.2.3 on 2021-08-12 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControlProyecto', '0008_alter_workflow_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoitem',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ControlProyecto.workflow'),
        ),
    ]
